DEG_analyze2/DEG_analyze2/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.views.static import serve
# import xadmin

from app_users.views import LoginView, LogoutView, RegisterView, AciveUserView, ForgetPwdView, ResetView, ModifyPwdView
from DEG_analyze2.settings import MEDIA_ROOT, STATIC_ROOT
# from users.views import IndexView

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url('^$', TemplateView.as_view(template_name= "index.html"),name="index"),
    url('^login/$', LoginView.as_view(), name="login"),
    url('^logout/$', LogoutView.as_view(), name="logout"),
    url('^register/$', RegisterView.as_view(), name="register"),
    url(r'^captcha/',include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$',AciveUserView.as_view(),name="user_active"),
    url(r'^forget/$', ForgetPwdView.as_view(), name="forget_pwd"),
    url(r'^reset/(?P<active_code>.*)/$',ResetView.as_view(),name="reset_pwd"),
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name="modify_pwd"),

    #用户相关url配置
    url(r'^users/',include(('app_users.urls', 'app_users'), namespace="users")),

    #方法相关url配置
    url(r'^methods/',include(('app_methods.urls', 'app_methods'), namespace="methods")),

    #操作相关url配置
    url(r'^operation/',include(('app_operation.urls', 'app_operation'), namespace="operation")),

    #DEBGU为FALSE时添加static的路由
    # url(r'^static/(?P<path>.*)$',  serve, {"document_root":STATIC_ROOT}),

    #配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$',  serve, {"document_root":MEDIA_ROOT}),
]


#全局404页面配置
handler404 = 'app_users.views.page_not_found'
handler500 = 'app_users.views.page_error'

DEG_analyze2/app_methods/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include

from .views import MethodListView, MethodDetailView


urlpatterns = [
    #方法列表页
    url(r'^list/$', MethodListView.as_view(), name="methods_list"),

    #方法详情页
    url(r'^detail/(?P<method_id>\d+)/$', MethodDetailView.as_view(), name="method_detail"),
]

DEG_analyze2/app_users/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include

from .views import UserinfoView, UploadImageView ,UpdatePwdView, SendEmailCodeView, UpdateEmailView
from .views import MyHistoryView, MymessageView


urlpatterns = [
    #用户信息
    url(r'^info/$', UserinfoView.as_view(), name="user_info"),

    #用户头像上传
    url(r'^image/upload/$', UploadImageView.as_view(), name="image_upload"),

    #用户个人中心修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name="update_pwd"),

    #发送邮箱验证码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name="sendemail_code"),

    #修改邮箱
    url(r'^update_email/$', UpdateEmailView.as_view(), name="update_email"),

    #我的历史
    url(r'^myhistory/$', MyHistoryView.as_view(), name="myhistory"),

    #我的消息
    url(r'^mymessage/$', MymessageView.as_view(), name="mymessage"),
]

DEG_analyze2/app_users/forms.py
# -*- coding: utf-8 -*-
from django import forms
from captcha.fields import CaptchaField

from .models import UserProfile

class LoginForm(forms.Form):  #必须和login的html里面的名称一致
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=5)


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)
    captcha = CaptchaField(error_messages={"invalid":u"验证码错误"})


class ForgetForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={"invalid":u"验证码错误"})


class ModifyPwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'gender', 'birday', 'address', 'mobile']

DEG_analyze2/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>链接失效</p>
</body>
</html>

DEG_analyze2/templates/index.html
{% extends 'base.html' %} {% block title %}DEGS 首页{% endblock %} {% load staticfiles %} {% block custom_bread %} {% endblock %} {% block custom_js %}
<script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %} {% block content %}
<div class="banner">
    <div class="wp">
        <div class="fl">
            <div class="imgslide">
                <ul class="imgs">
                    <li>
                        <a href="">
                            <img width="1200" height="478" src="/static/images/guide1.PNG" />
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <img width="1200" height="478" src="/static/images/guide2.PNG" />
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <img width="1200" height="478" src="/static/images/guide3.PNG" />
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <img width="1200" height="478" src="/static/images/guide4.PNG" />
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <img width="1200" height="478" src="/static/images/guide5.PNG" />
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'methods:methods_list' %}">
                            <img width="1200" height="478" src="/static/images/guide6.PNG" />
                        </a>
                    </li>
                </ul>
            </div>
            <div class="unslider-arrow prev"></div>
            <div class="unslider-arrow next"></div>
        </div>

    </div>


</div>

<section>
    <div class="wp">
        <ul class="feature">
            <li class="feature1">
                <img class="pic" src="/static/images/feature1.png" />
                <p class="center">快速开始</p>
            </li>
            <li class="feature2">
                <p class="text" style=" text-align:center;line-height:20px;">您可以在认真观看完轮播图后，按照图中最后一页的提示内容，采用此方法快速开始处理您的原文件。在使用该方式时，我们将不会记录您的任何使用记录，无法保留您上传的文件以及处理的结果，且平台的部分功能将不被支持，若数据意外丢失将无法找回。</p>
            </li>
            <li class="feature3">
                <img class="pic" src="/static/images/feature3.png" />
                <p class="center">登录注册</p>
            </li>
            <li class="feature4">
                <p class="text" style=" text-align:center;line-height:20px;">您可以在认真观看完轮播图后，点击页面右上方注册按钮进行本平台的账号注册，在登录状态下处理您的原文件。使用该方式时，您可以在 “个人中心” 中查看您的常用方法、常用参数、上传文件和处理结果等。若有需求还可以通过留言功能与后台人员交流。</p>
            </li>
        </ul>
    </div>
</section>
{% endblock %}

DEG_analyze2/templates/method-1001.html
{% extends 'base.html' %} {% block title %}方法详情 - DEGs{% endblock %} {% load staticfiles %} {% block custom_bread %}
<section>
    <div class="wp">
        <ul class="crumbs">
            <li><a href="/">首页</a>></li>
            <li><a href="{% url 'methods:methods_list' %}">方法列表</a>></li>
            <li>方法详情</li>
        </ul>
    </div>
</section>
{% endblock %} {% block content %}
<section>
    <div class="wp butler-detail-box butler-diaryd-box clearfix">
        <div class="fl list">

            <div class="butler_detail_list clearfix">
                <div class="brief">
                    <dl class="des">
                        <dt>
                            <div class="picpic">
                                <img width="100" height="100" src="/static/images/method.jpg"/>
                            </div>
                        </dt>
                        <dd>
                            <a href="">
                                <h1>{{ method.method_name }}</h1>
                            </a>
                            <ul class="cont">
                                <li>方法详情：<span>{{ method.method_detail }}</span></li>
                                <li>常用参数：<span>{{ method.args }}</span></li>
                                <li>要求文件格式：<span>&nbsp;</span></li>
                                <img width="600" height="80" src="/static/images/RNAseq_data.jpg" />
                            </ul>
                        </dd>
                    </dl>
                </div>
            </div>

            <div class="butler_detail_cont clearfix">
                <div class="left layout">
                    <div class="head">
                        <ul class="tab_header">
                            <li class="active"><a href="">上传文件</a> </li>
                        </ul>
                    </div>
                    <div class="companycenter">
                        <div style="padding-top:30px; text-align: center; padding-bottom: 30px;">
                            <form>
                                {% csrf_token %}
                                <input type="file" id="file">
                                <input type="button" id="submit" style="width:100px; height:30px;" value="上传文件">
                            </form>
                            <div style="display: none;" id="loading1">
                                <img width="200" height="110" src="/static/images/loading.gif" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="butler_detail_cont clearfix">
                <div class="left layout">
                    <div class="head">
                        <ul class="tab_header">
                            <li class="active"><a href="">填写参数</a> </li>
                        </ul>
                    </div>
                    <div class="companycenter">
                        <div style="display: none;" id="AddArgs">
                            <div style="padding-top:30px; text-align: center; padding-bottom: 30px;">
                                <form>
                                    {% csrf_token %}
                                    <label style="font-size:small;">p_value < 
                                        <input type="text" placeholder="请输入参数" id="p_value">
                                        </label>
                                    <input type="button" id="submitArgs" style="width:100px; height:30px;" value="提交">
                                </form>
                                <div style="display: none;" id="loading2">
                                    <img width="200" height="110" src="/static/images/loading.gif" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<script>
    $(function() {
        $('#submit').click(function() {
            //ajax上传文件必须通过FormData对象传输数据
            var formdata = new FormData();

            var csrf_data = $('input[name=csrfmiddlewaretoken]').val();
            //获取上传文件对象(文件句柄)：定位对象，转成DOM对象，取值(文件对象列表)
            var file = $('#file')[0].files[0];
            if ($("#file").val() == "") {
                alert('请选择上传的文件！');
                return false;
            }
            var filepath = document.getElementById("file").value;
            var fileend = filepath.substring(filepath.lastIndexOf("."));
            if (fileend != ".csv") {
                alert('不接受此文件类型,请上传csv格式的文件！\r\n');
                return false;
            }

            formdata.append("method_type", "For RNAseq data");
            formdata.append("method_id", "1001");
            formdata.append('csrfmiddlewaretoken', csrf_data); //csrf认证的键是固定的
            formdata.append('file', file);

            $.ajax({
                url: "/operation/uploadfile/",
                type: 'post',
                data: formdata,
                processData: false, //不处理数据
                contentType: false, //不设置内容类型，按原格式传输
                beforeSend: function(XMLHttpRequest) {
                    document.getElementById("loading1").style.display = "block";
                },
                success: function(arg) {
                    document.getElementById("loading1").style.display = "none";
                    alert(arg.msg);
                    if (arg.status == "success")
                        document.getElementById("AddArgs").style.display = "block";
                }
            })
        })

        $('#submitArgs').click(function() {
            //ajax上传文件必须通过FormData对象传输数据
            var formdata = new FormData();

            var csrf_data = $('input[name=csrfmiddlewaretoken]').val();
            var p_value = $("#p_value").val();
            if (p_value == "") {
                alert('请输入参数！');
                return false;
            }
            if (p_value < 0 || p_value > 0.5) {
                alert('确保参数p_value的取值在0 ~ 0.5之间，太大p值将失去意义！');
                return false;
            }

            formdata.append("method_type", "For RNAseq data");
            formdata.append("method_id", "1001");
            formdata.append('csrfmiddlewaretoken', csrf_data); //csrf认证的键是固定的
            formdata.append('p_value', p_value);

            $.ajax({
                url: "/operation/check/",
                type: 'post',
                data: formdata,
                processData: false, //不处理数据
                contentType: false, //不设置内容类型，按原格式传输
                beforeSend: function(XMLHttpRequest) {
                    document.getElementById("loading2").style.display = "block";
                },
                success: function(arg) {
                    document.getElementById("loading2").style.display = "none";
                    alert('参数提交成功，点击确定后跳转结果页面!');
                    if (arg.msg == '111')
                        location.href = "/operation/result_RNA1/";
                    else
                        location.href = "/operation/result_RNA0/";
                }
            })
        })

    })
</script>
<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>

{% endblock %}

DEG_analyze2/templates/method-1003.html
{% extends 'base.html' %} {% block title %}方法详情 - DEGs{% endblock %} {% load staticfiles %} {% block custom_bread %}
<section>
    <div class="wp">
        <ul class="crumbs">
            <li><a href="/">首页</a>></li>
            <li><a href="{% url 'methods:methods_list' %}">方法列表</a>></li>
            <li>方法详情</li>
        </ul>
    </div>
</section>
{% endblock %} {% block content %}
<section>
    <div class="wp butler-detail-box butler-diaryd-box clearfix">
        <div class="fl list">

            <div class="butler_detail_list clearfix">
                <div class="brief">
                    <dl class="des">
                        <dt>
                            <div class="picpic">
                                <img width="100" height="100" src="/static/images/method.jpg"/>
                            </div>
                        </dt>
                        <dd>
                            <a href="">
                                <h1>{{ method.method_name }}</h1>
                            </a>
                            <ul class="cont">
                                <li>方法详情：<span>{{ method.method_detail }}</span></li>
                                <li>常用参数：<span>{{ method.args }}</span></li>
                                <li>要求文件格式：<span>&nbsp;</span></li>
                                <img width="600" height="80" src="/static/images/RNAseq_data.jpg" />
                            </ul>
                        </dd>
                    </dl>
                </div>
            </div>

            <div class="butler_detail_cont clearfix">
                <div class="left layout">
                    <div class="head">
                        <ul class="tab_header">
                            <li class="active"><a href="">上传文件</a> </li>
                        </ul>
                    </div>
                    <div class="companycenter">
                        <div style="padding-top:30px; text-align: center; padding-bottom: 30px;">
                            <form>
                                <input type="file" id="file">
                                <input type="button" id="submit" style="width:100px; height:30px;" value="上传文件"> {% csrf_token %}
                            </form>
                            <div style="display: none;" id="loading1">
                                <img width="200" height="110" src="/static/images/loading.gif" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="butler_detail_cont clearfix">
                <div class="left layout">
                    <div class="head">
                        <ul class="tab_header">
                            <li class="active"><a href="">填写参数</a> </li>
                        </ul>
                    </div>
                    <div class="companycenter">
                        <div style="display: none;" id="AddArgs">
                            <div style="padding-top:30px; text-align: center; padding-bottom: 30px;">
                                <form>
                                    <label style="font-size:small;">FDR < 
                                        <input type="text" placeholder="请输入参数" id="FDR">
                                        </label>
                                    <input type="button" id="submitArgs" style="width:100px; height:30px;" value="提交"> {% csrf_token %}
                                </form>
                                <div style="display: none;" id="loading2">
                                    <img width="200" height="110" src="/static/images/loading.gif" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<script>
    $(function() {
        $('#submit').click(function() {
            //ajax上传文件必须通过FormData对象传输数据
            var formdata = new FormData();

            var csrf_data = $('input[name=csrfmiddlewaretoken]').val();
            //获取上传文件对象(文件句柄)：定位对象，转成DOM对象，取值(文件对象列表)
            var file = $('#file')[0].files[0];
            if ($("#file").val() == "") {
                alert('请选择上传的文件！');
                return false;
            }
            var filepath = document.getElementById("file").value;
            var fileend = filepath.substring(filepath.lastIndexOf("."));
            if (fileend != ".csv") {
                alert('不接受此文件类型,请上传csv格式的文件！\r\n');
                return false;
            }

            formdata.append("method_type", "For RNAseq data");
            formdata.append("method_id", "1003");
            formdata.append('csrfmiddlewaretoken', csrf_data); //csrf认证的键是固定的
            formdata.append('file', file);

            $.ajax({
                url: "/operation/uploadfile/",
                type: 'post',
                data: formdata,
                processData: false, //不处理数据
                contentType: false, //不设置内容类型，按原格式传输
                beforeSend: function(XMLHttpRequest) {
                    document.getElementById("loading1").style.display = "block";
                },
                success: function(arg) {
                    document.getElementById("loading1").style.display = "none";
                    alert(arg.msg)
                    if (arg.status == "success")
                        document.getElementById("AddArgs").style.display = "block";
                }
            })
        })

        $('#submitArgs').click(function() {
            //ajax上传文件必须通过FormData对象传输数据
            var formdata = new FormData();

            var csrf_data = $('input[name=csrfmiddlewaretoken]').val();
            var FDR = $("#FDR").val();
            if (FDR == "") {
                alert('请输入参数！');
                return false;
            }
            if (FDR < 0 || FDR > 0.5) {
                alert('确保参数FDR的取值在0 ~ 0.5之间，太大FDR值将失去意义！');
                return false;
            }

            formdata.append("method_type", "For RNAseq data");
            formdata.append("method_id", "1003");
            formdata.append('csrfmiddlewaretoken', csrf_data); //csrf认证的键是固定的
            formdata.append('FDR', FDR);

            $.ajax({
                url: "/operation/check/",
                type: 'post',
                data: formdata,
                processData: false, //不处理数据
                contentType: false, //不设置内容类型，按原格式传输
                beforeSend: function(XMLHttpRequest) {
                    document.getElementById("loading2").style.display = "block";
                },
                success: function(arg) {
                    document.getElementById("loading2").style.display = "none";
                    alert('参数提交成功，点击确定后跳转结果页面!');
                    if (arg.msg == '111')
                        location.href = "/operation/result_RNA1/";
                    else
                        location.href = "/operation/result_RNA0/";
                }
            })
        })

    })
</script>
<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>

{% endblock %}

DEG_analyze2/templates/send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>邮件已发送， 请查收</p>

</body>
</html>

DEG_analyze2/templates/usercenter-info.html
{% extends 'usercenter-base.html' %} {% block title %}个人信息{% endblock %} {% block custom_bread %}
<section>
    <div class="wp">
        <ul class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
            <li>个人信息</li>
        </ul>
    </div>
</section>
{% endblock %} {% block left_content %}
<div class="left">
    <ul>
        <li class="active2"><a href="{% url 'users:user_info' %}">个人资料</a></li>
        <li>
            <a href="{% url 'users:mymessage' %}" style="position: relative;">
        我的消息
    </a>
        </li>
        <li>
            <a href="{% url 'users:myhistory' %}" style="position: relative;">
        我的历史
    </a>
        </li>
    </ul>
</div>
{% endblock %} {% block right_content %}
<div class="right">
    <div class="personal_des ">
        <div class="head" style="border:1px solid #eaeaea;">
            <h1>个人信息</h1>
        </div>
        <div class="inforcon">
            <div class="left" style="width:242px;">
                <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'users:image_upload' %}" target='frameFile'>
                    <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                            </span>
                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                            </span>
                        </label> {% csrf_token %}
                </form>
                <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                    <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                </div>
            </div>
            <form class="perinform" id="jsEditUserForm" autocomplete="off">
                <ul class="right">
                    <li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                        <input type="text" name="nick_name" id="nick_name" value="{{ request.user.nick_name }}" maxlength="10">
                        <i class="error-tips"></i>
                    </li>
                    <li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                        <input type="text" id="birth_day" name="birday" value="{{ request.user.birday }}" readonly="readonly" />
                        <i class="error-tips"></i>
                    </li>
                    <li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
                        <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"  name="gender" value="male" {% if request.user.gender == 'male' %}checked="checked"{% endif %}>男</label>
                        <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="female" {% if request.user.gender == 'female' %}checked="checked"{% endif %}>女</label>
                    </li>
                    <li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                        <input type="text" name="address" id="address" placeholder="请输入你的地址" value="{{ request.user.address }}" maxlength="10">
                        <i class="error-tips"></i>
                    </li>
                    <li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                        <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码" value="{{ request.user.mobile|default_if_none:'' }}" maxlength="10">
                    </li>
                    <li>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：
                        <input class="borderno" type="text" name="email" readonly="readonly" value="{{ request.user.email }}" />
                        <span class="green changeemai_btn">[修改]</span>
                    </li>
                    <li class="button heibtn">
                        <input type="button" id="jsEditUserBtn" value="保存">
                    </li>
                </ul>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

DEG_analyze2/templates/usercenter-message.html
{% extends 'usercenter-base.html' %} {% block title %}我的消息- DEGs{% endblock %} {% load staticfiles %} {% block custom_bread %}
<section>
    <div class="wp">
        <ul class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
            <li>我的消息</li>
        </ul>
    </div>
</section>
{% endblock %} {% block left_content %}
<div class="left">
    <ul>
        <li><a href="{% url 'users:user_info' %}">个人资料</a></li>
        <li class="active2">
            <a href="{% url 'users:mymessage' %}" style="position: relative;">
        我的消息
    </a>
        </li>
        <li>
            <a href="{% url 'users:myhistory' %}" style="position: relative;">
        我的历史
    </a>
        </li>
    </ul>
</div>
{% endblock %} {% block right_content %}
<div class="right">
    <div class="personal_des Releasecont">
        <div class="head">
            <h1>我的消息</h1>
        </div>

    </div>
    <div class="personal_des permessage">
        <div class="head">
            <ul class="tab_header messagehead">
                <li class="active"><a href="{% url 'users:mymessage' %}">个人消息</a> </li>
            </ul>


        </div>
        <div class="messagelist">
            {% for message in messages.object_list %}
            <div class="messages">
                <div class="fr">
                    <div class="top"><span class="fl time">{{ message.add_time }}</span><span class="fr btn foldbtn"></span></div>
                    <p>
                        {{ message.message }}
                    </p>
                </div>
            </div>
            {% endfor %}
        </div>


        <div class="pageturn pagerright">
            <ul class="pagelist">
                {% if messages.has_previous %}
                <li class="long"><a href="?{{ messages.previous_page_number.querystring }}">上一页</a></li>
                {% endif %} {% for page in messages.pages %} {% if page %} {% ifequal page messages.number %}
                <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                {% else %}
                <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                {% endifequal %} {% else %}
                <li class="none"><a href="">...</a></li>
                {% endif %} {% endfor %} {% if messages.has_next %}
                <li class="long"><a href="?{{ messages.next_page_number.querystring }}">下一页</a></li>
                {% endif %}

            </ul>
        </div>
    </div>

</div>
{% endblock %}

DEG_analyze2/templates/usercenter-myhistory.html
{% extends 'usercenter-base.html' %} {% block title %}我的历史- DEGs{% endblock %} {% load staticfiles %} {% block custom_bread %}
<section>
    <div class="wp">
        <ul class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
            <li>我的历史</li>
        </ul>
    </div>
</section>
{% endblock %} {% block left_content %}
<div class="left">
    <ul>
        <li><a href="{% url 'users:user_info' %}">个人资料</a></li>
        <li>
            <a href="{% url 'users:mymessage' %}" style="position: relative;">
        我的消息
    </a>
        </li>
        <li class="active2">
            <a href="{% url 'users:myhistory' %}" style="position: relative;">
        我的历史
    </a>
        </li>
    </ul>
</div>
{% endblock %} {% block right_content %}
<div class="right">
    <div class="personal_des Releasecont">
        <div class="head">
            <h1>我的历史</h1>
        </div>

    </div>
    <div class="personal_des permessage">
        <div class="messagelist">
            {% for history in historys.object_list %}
            <div class="messages">
                <div class="fr">
                    <div class="top"><span class="fl time">{{ history.use_time }}</span><span class="fr btn foldbtn"></span></div>
                    <p>
                        <a href="{{ MEDIA_URL }}{{ history.upload_file }}" class="downcode" target="_blank" download="" data-id="274" title="">上传文件（点击下载）</a> 使用方法编号：{{ history.method_id }} 使用参数：{{ history.args_choose }}
                    </p>
                </div>
            </div>
            {% endfor %}
        </div>


        <div class="pageturn pagerright">
            <ul class="pagelist">
                {% if historys.has_previous %}
                <li class="long"><a href="?{{ historys.previous_page_number.querystring }}">上一页</a></li>
                {% endif %} {% for page in historys.pages %} {% if page %} {% ifequal page historys.number %}
                <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                {% else %}
                <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                {% endifequal %} {% else %}
                <li class="none"><a href="">...</a></li>
                {% endif %} {% endfor %} {% if historys.has_next %}
                <li class="long"><a href="?{{ historys.next_page_number.querystring }}">下一页</a></li>
                {% endif %}

            </ul>
        </div>
    </div>

</div>
{% endblock %}